### ISSUE TITLE
Unable to run the quick-start  

### ISSUE THREAD

**Issue by Vickzhang** [phurwicz/hover#10]
I tried to run the quick start code, but  jupyter show nothing after I run:

```python
from bokeh.io import show, output_notebook
output_notebook()
show(handle)
```

Did I miss something？

**Comment by phurwicz** [comment]
Hi Vick,

This is possibly because your Jupyter notebook is on a port other than the default `localhost:8888`. Could you try passing `notebook_url="http://localhost:<port>"` to the kwargs of `show()`?

[Reference](https://github.com/bokeh/bokeh/blob/branch-2.3/examples/howto/server_embed/notebook_embed.ipynb)

**Comment by Vickzhang** [comment]
Thanks, phurwicz. That works for me to pass the notebook_url param.
