### ISSUE TITLE
Add support for higher dimensionality than 2

### ISSUE THREAD

**Issue by Hellisotherpeople** [phurwicz/hover#19]
As we all know, as amazing as algorithms like UMAP are, they are still missing massive amounts of explained variance compared to significantly higher N levels of dimensionality. This is why the dimensionality of "word vectors" or of embeddings in general continues to go up... it really does improve the down-stream performance of the model. 

I am not sure as to how refined Bokeh is with user editable 3D plots, but it should be explored. I defenitely implemented this sort of functionality (poorly) with Matplotlib on a 3D scatterplot back in 2018 for my [own text-project](https://raw.githubusercontent.com/Hellisotherpeople/CX_DB8/master/cool_graph.gif)

Besides being even cooler for users - this would make the ideal use-cases of this model (fast data-labeling, effective active learning) far far better. Consider implementing this as a large number of 2D scatterplots plotting various dimensions against each other if 3D scatterplots won't work within Bokeh.

**Comment by phurwicz** [comment]
Thank you and indeed having just 2 dimensions limits the amount of information. Something that comes to mind, if 3d display turns out not working out (for instance, making selections can be problematic), would be to allow *N* dimensions and have the user specify which ones to look at through a widget. How does that sound?

**Comment by phurwicz** [comment]
I think I will go ahead with the N-dimension-choose-2-for-display approach. Sketch for implementation:

`hover.core.SupervisableDataset.compute_nd_embedding`: similar to `compute_2d_embedding` but for N dimensions. Also, the naming of output columns will be different -- something like "embedding_f0" to "embedding_f9" rather than "x" and "y".

`hover.core.explorer.functionality.BokehMultiAxisExplorer`: an explorer class specifically for choosing which embedding axes to use for 2D plot. 
- I have considered whether to bake multiple-axis support into the base class of explorers. My argument is that higher dimensionality is helpful but not essential enough to justify another set of widgets (for choosing axes) for every explorer. On the other hand, it should suffice to use a separate explorer for high dimensions, where selections are synchronized across explorers.

**Comment by phurwicz** [comment]
Implemented and released with 0.7.0.

**Comment by phurwicz** [comment]
Hi @Hellisotherpeople, it's been a while but this feature is now available. 

[This section of the tutorial](https://phurwicz.github.io/hover/pages/tutorial/t4-annotator-dataset-interaction/#change-plot-axes) shows you the widget to change axes.
