### ISSUE TITLE
multi labeling

### ISSUE THREAD

**Issue by robinsonkwame** [phurwicz/hover#44]
I probably overlooked it somewhere but does Hover support multi labeling? As a kludge I can create new labels with commas between them but I'd thought I'd ask here.

**Comment by haochuanwei** [comment]
It does not, because right now the colors on the markers would be confused. If you can think of a way for colors to effectively indicate multiple labels, that would be fantastic.

For kludges, I would suggest applying one kind of label at a time (one csv per label), and then joining the results.

Best regards,
Haochuan
________________________________
From: Kwame Porter Robinson ***@***.***>
Sent: Thursday, August 18, 2022 5:14:53 AM
To: phurwicz/hover ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phurwicz/hover] multi labeling (Issue #44)


I probably overlooked it somewhere but does Hover support multi labeling? As a kludge I can create new labels with commas between them but I'd thought I'd ask here.

**Comment by robinsonkwame** [comment]
To indicate multiple labels with color you could map a single color to a set of labels and not reuse that color elsewhere.  For example green --> historical and sport labels. But I'll either label one at a time or use commas.
