### ISSUE TITLE
Accepting Huggingface transformers

### ISSUE THREAD

**Issue by robinsonkwame** [phurwicz/hover#50]
Does Hover include abstractions over text vectorizers? I wanted to use huggingface models, `all-MiniLM-L6-v2` specifically over Spacy, for vectorizing text and made a facade class; I thought I could contribute it but I'm not sure.

Using huggingface would require `sentencetransformers` and there might not be class abstractions over text (or otherwise) vectorizers?

**Comment by phurwicz** [comment]
Yes, you can use any vectorizer, hover just expects a function with "feature: str -> vector: np.ndarray" signature.

Could you elaborate a bit on why we need class abstractions? I ask because hover is vectorizer-agnostic. If you need something like `model.predict(*some_args_different_from_expected_signature)` you can simply wrap that as a `vectorizer` function.

Example of creating a custom vectorizer, adding regex preprocessing on top of Spacy: https://github.com/phurwicz/hover/blob/602ba8a244266894ef821025dc0e618170b380b0/fixture_module/text_vector_net/__init__.py#L14-L43

Similarly you can load up `all-MiniLM-L6-v2` in the `get_vectorizer` scope and return a `vectorizer` function to be used later.

**Comment by robinsonkwame** [comment]
Ah, didn't realize hover was vectorizer agnostic! No need for abstractions, classes, etc then, the coder just brings their own.
